const languageMap: Record<string, string> = {
  // Languages with more than ~700 books. TIL that Open Library uses the ISO 639-2/B standard for its language codes
  eng: 'English',
  ger: 'German',
  fre: 'French',
  spa: 'Spanish',
  rus: 'Russian',
  ita: 'Italian',
  chi: 'Chinese',
  jpn: 'Japanese',
  ara: 'Arabic',
  por: 'Portuguese',
  heb: 'Hebrew',
  kor: 'Korean',
  pol: 'Polish',
  dut: 'Dutch',
  lat: 'Latin',
  ind: 'Indonesian',
  swe: 'Swedish',
  tur: 'Turkish',
  und: 'Undetermined',
  hun: 'Hungarian',
  per: 'Persian',
  dan: 'Danish',
  ukr: 'Ukrainian',
  urd: 'Urdu',
  cze: 'Czech',
  hin: 'Hindi',
  cmn: 'Mandarin',
  gre: 'Modern Greek',
  rum: 'Romanian',
  bul: 'Bulgarian',
  vie: 'Vietnamese',
  cat: 'Catalan',
  nor: 'Norwegian',
  hrv: 'Croatian',
  fin: 'Finnish',
  ben: 'Bengali',
  tha: 'Thai',
  srp: 'Serbian',
  yid: 'Yiddish',
  mul: 'Multiple languages',
  tam: 'Tamil',
  tib: 'Tibetan',
  arm: 'Armenian',
  guj: 'Gujarati',
  mar: 'Marathi',
  wel: 'Welsh',
  pan: 'Punjabi',
  slo: 'Slovak',
  tel: 'Telugu',
  san: 'Sanskrit',
  may: 'Malay',
  slv: 'Slovene',
  kan: 'Kannada',
  grc: 'Ancient Greek',
  alb: 'Albanian',
  mal: 'Malayalam',
  lit: 'Lithuanian',
  bur: 'Burmese',
  geo: 'Georgian',
  lav: 'Latvian',
  afr: 'Afrikaans',
  mac: 'Macedonian',
  est: 'Estonian',
  nep: 'Nepali',
  mon: 'Mongolian',
  aze: 'Azerbaijani',
  bel: 'Belarusian',
  gle: 'Irish',
  ori: 'Odia',
  gem: 'Germanic (Other)',
  ice: 'Icelandic',
  uzb: 'Uzbek',
  sin: 'Sinhala',
  kur: 'Kurdish',
  kaz: 'Kazakh',
  ota: 'Turkish, Ottoman',
  snd: 'Sindhi',
  glg: 'Galician',
  bos: 'Bosnian',
  pus: 'Pashto',
  kir: 'Kyrgyz',
  asm: 'Assamese',
  swa: 'Swahili',
  amh: 'Amharic',
  tgk: 'Tajik',
  tat: 'Tatar',
  tgl: 'Tagalog',
  baq: 'Basque',
  gla: 'Scottish Gaelic',
  tut: 'Altaic (Other)',
  bak: 'Bashkir',
  tuk: 'Turkmen',
  nob: 'Bokmål',
  chv: 'Chuvash',
  jav: 'Javanese',
  khm: 'Khmer',
  fiu: 'Finno-Ugrian (Other)',
  raj: 'Rajasthani',
  lao: 'Lao',
  hau: 'Hausa',
  roh: 'Romansh',
  syr: 'Syriac, Modern',
  epo: 'Esperanto',
  cau: 'Caucasian (Other)',
  pli: 'Pali',
  enm: 'English, Middle (1100-1500)',
  nic: 'Niger-Kordofanian (Other)',
  map: 'Austronesian (Other)',
  mai: 'Maithili',
  kok: 'Konkani',
  uig: 'Uyghur',
  new: 'Newari',
  frm: 'French, Middle (ca. 1300-1600)',
  mlt: 'Maltese',
  sit: 'Sino-Tibetan (Other)',
  yor: 'Yoruba',
  inc: 'Indic (Other)',
  chu: 'Church Slavonic',
  fro: 'French, Old (ca. 842-1300)',
  roa: 'Romance (Other)',
  fry: 'West Frisian',
  som: 'Somali',
  mlg: 'Malagasy',
  fao: 'Faroese',
  gmh: 'German, Middle High (ca. 1050-1500)',
  bre: 'Breton',
  sai: 'South American Indian (Other)',
  myn: 'Mayan languages',
  oci: 'Occitan',
  wen: 'Sorbian (Other)',
  sun: 'Sundanese',
  zul: 'Zulu',
}

export default languageMap
